# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [15.x]
=======
        node-version: [10.x, 12.x, 14.x, 15.x]
>>>>>>> c33db05 (Create node.js.yml)
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup and run backend tests
      working-directory: ./backend
      run: |
          npm ci
          npm run build --if-present
          npm test
    - name: Setup and run frontend tests
      working-directory: ./frontend
      run: |
          npm ci
          npm run build --if-present
          npm test
